services:

  frontend:
    container_name: fwe-gotdle-frontend
    image: registry.code.fbi.h-da.de/sthiohnoo/gotdle/frontend:latest
    ports:
      - 0.0.0.0:5173:5173
    networks:
      - default
    env_file:
      - .env.frontend

  backend:
    container_name: fwe-gotdle-backend
    image: registry.code.fbi.h-da.de/sthiohnoo/gotdle/backend:latest
    ports:
      - 0.0.0.0:3000:3000
    networks:
      - default
    env_file:
      - .env.backend
    command: sh -c "npm run db:migrate && npm start"
    depends_on:
      - fwe-gotdle-db


  fwe-gotdle-db:
    image: postgres:latest
    container_name: fwe-gotdle-db
    restart: always
    environment:
      POSTGRES_DB: gotdle_db
      POSTGRES_USER: gotdle_user
      POSTGRES_PASSWORD: topSecret!
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'gotdle_user', '-d', 'gotdle_db']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - fwe-gotdle-db-data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  fwe-gotdle-db-data:
    driver: local

networks:
  default:
    driver: bridge
