version: '3.8'

services:
  fwe-gotdle-db:
    image: postgres:latest
    container_name: fwe-gotdle-db
    restart: always
    environment:

      POSTGRES_DB: gotdle_db
      POSTGRES_USER: gotdle_user
      POSTGRES_PASSWORD: topSecret!
    ports:
      - 5432:5432
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'gotdle_user', '-d', 'gotdle_db' ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - fwe-gotdle-db-data:/var/lib/postgresql/data

volumes:
  fwe-gotdle-db-data:
    driver: local
